version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./media:/media
    environment:
      - DB_DIALECT=sqlite3
      - DEBUG=true
      - REQUEST_FULL_SYNC=false
      - PROGRAM_ID=111
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
