version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8080"
    volumes:
      - ./data:/data
      - ./media:/media
    environment:
      - DB_DIALECT=sqlite3
      - DEBUG=true
      - REQUEST_FULL_SYNC=false
      - PROGRAM_ID=ADMIN
      - DEPO_URL=https://devapi.courstore.com/v1/dialog
      - API_URL=https://devapi.courstore.com/v1
      - TG_URL=https://devtg.courstore.com/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
