### Send message
POST http://142.93.142.126:8088/send
Content-Type: application/json

{"JID": "77086848720", "Text": "❗️ Ваш код подтверждения *306777*"}

### Check contact
POST http://localhost:8080/check-user
Content-Type: application/json

{
  "phone_number": "+84913248745"
}

### Send message
POST http://sandbox.courstore.com:8081/send
Content-Type: application/json

{
  "jid": "77785080094",
  "text": "Choose an option:"
}